// This file will be generated by: supabase gen types typescript --project-id <project-id> > src/lib/supabase/database.types.ts
// For now, we'll create a placeholder that will be replaced when migrations are run

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          avatar_url: string | null;
          role: 'admin' | 'manager' | 'user';
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      contacts: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          emails: Json;
          phones: Json;
          addresses: Json;
          job_title: string | null;
          description: string | null;
          tags: string[];
          avatar_url: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['contacts']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['contacts']['Insert']>;
      };
      // Add other tables as needed - this will be auto-generated from Supabase
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: 'admin' | 'manager' | 'user';
      organization_type: 'company' | 'fund' | 'agency' | 'non_profit' | 'government' | 'other';
      role_type: 'executive' | 'employee' | 'founder' | 'board_member' | 'advisor' | 'investor' | 'consultant' | 'partner' | 'other';
      business_relationship_type: 'b2b_client' | 'b2c_client' | 'non_business_investment' | 'business_investment_external' | 'internal_business_opportunity' | 'portfolio_company' | 'partnership_opportunity' | 'individual_partnership' | 'investor' | 'meridian_44_participant';
      task_type: 'call' | 'email' | 'text' | 'meeting' | 'send_mailer' | 'other';
      task_status: 'pending' | 'completed' | 'triaged' | 'dismissed';
      cadence_status: 'active' | 'paused' | 'completed' | 'cleared';
      activity_type: 'call_inbound' | 'call_outbound' | 'email_inbound' | 'email_outbound' | 'text_inbound' | 'text_outbound' | 'meeting_in_person' | 'meeting_virtual' | 'note' | 'stage_change' | 'relationship_created' | 'cadence_applied' | 'cadence_cleared' | 'cadence_paused' | 'cadence_resumed' | 'task_completed' | 'task_triaged' | 'task_dismissed';
      venture: 'forge' | 'hearth' | 'anvil' | 'crucible' | 'foundry' | 'carbide' | 'lucepta' | 'meridian_44' | 'trade_stone_group';
    };
  };
}

